project_id = "purbhxibouvtmgtsoidh"

[functions.kadig-ai-chat]
verify_jwt = false

[functions.market-data]
verify_jwt = false

[functions.market-analysis]
verify_jwt = false

[functions.update-prices]
verify_jwt = false

[functions.portfolio-snapshot]
verify_jwt = false

[functions.recommended-portfolios]
verify_jwt = false

[functions.market-reports]
verify_jwt = false

[functions.kadig-index]
verify_jwt = false

[functions.pluggy]
verify_jwt = false
